In [153]:
#IMPORTING LIBRARIES
import pandas as pd
import time
#FOR SPLITING DATA
from sklearn.model_selection import train_test_split
# FOR CONFUSION MATRIX
from sklearn.metrics import confusion_matrix
#IMPORTING ALL MODELS FROM SKLEARN
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

# **Confusion Matrix**

In [154]:
# This function gives us the time value in miliseconds.
def current_milli_time():
    return round(time.time() * 1000)

# This function calculates the accuracy rate of a confusion matrix.
def calculate_AR(confusion_matrix):
    return (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])

def print_values(algorithm:str, accuracy_rate:float, training_time:int):
    print(algorithm, "Accuracy rate", accuracy_rate, "Training time:", training_time)

In [155]:
#LOADING DATASET
df = pd.read_csv("/content/titanic data.csv")

In [156]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked  \
0         1       1  female  38.0      1      0  0.139136        C   
1         1       1  female  35.0      1      0  0.103644        S   
2         0       1    male  54.0      0      0  0.101229        S   
3         1       3  female   4.0      1      1  0.032596        S   
4         1       1  female  58.0      0      0  0.051822        S   

               classification  cluster  
0             female survided        0  
1             female survided        0  
2   younger men  not survival        1  
3             female survided        2  
4             female survided        1

In [159]:
#SPLITING DATASET INTO TEST AND TRAIN MODEL
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

## Logistic Regression

In [161]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
 #LABEL ENCODER FOR CONVERTING STRING TO FLOAT
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])

# SPLITING DATA INTO FEARURES AND TARGET
X = df[['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex']]
y = df['classification']

#CREATING MODEL OF LOGISTIC REGRESSION
model = LogisticRegression()

#FITTING THE DATA IN MODEL
model.fit(X, y)

#PREDICTING THE CLASS LABEL FOR DATA
predictions = model.predict(X)

#ACCRACY OF REGRESSION
accuracy_regression = model.score(X, y)
print( model.score(X, y))



0.9791666666666666


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## Random Forest

In [163]:
#CALCULATING INITIAL TIME FOR CONFUSION MATRIX
rf_start_time = current_milli_time()
#RANDOM FOREST CLASSIFICATION OBJECT THAT CALCULATES GINI
rfc = RandomForestClassifier(n_estimators=100, criterion='gini')
#FITTING DATA INTO MODEL
rfc.fit(x_train, y_train)
#ENDING TIME OF MODEL TRAINING
rf_end_time = current_milli_time()
#TOTAL DURATION
rf_duration = rf_end_time - rf_start_time
#PREDICTING DATA
y_pred_rfc = rfc.predict(x_test)
#CONFUSION MATRIX
cm_rfc = confusion_matrix(y_test, y_pred_rfc)
#ACCURACY RATE
ar_rfc = calculate_AR(cm_rfc)
ar_rfc

0.7241379310344828

In [179]:
#PRINTNG CONFUSION MATRIX OF RANDOM FOREST
print(cm_rfc)

[[ 5  7]
 [ 1 16]]


## Naive Bayes

In [164]:
#NAIVE BAYES CLASSIFIER
#CALCULATING INITIAL TIME
nbstart_time = current_milli_time()
#NAIVE BAYES CLASSIFIER
gnb = GaussianNB()
#TRAINING DATA
gnb.fit(x_train,y_train)
#CALCULATING ENDING TIME
nbend_time = current_milli_time()
#CALCULATING TOTAL DURATION
NBduration = nbend_time - nbstart_time
#PREDICTING DATA
y_pred_nb = gnb.predict(x_test)
#CONFUSION MATRIX
cm_nb = confusion_matrix(y_test,y_pred_nb)
#CALCULATING ACCURACY RATE
ar_nb = calculate_AR(cm_nb)
ar_nb

0.7931034482758621

In [180]:
#CONFUSION MATRIX FOR NAIVE BAYES
print(cm_nb)

[[ 9  3]
 [ 3 14]]


## KNN Classifier

In [165]:
#KNN CLASSIFIER
#CALCULATING INITIAL TIME
knnstart_time = current_milli_time()
#CREATING OBJECT OF KNN CLASSIFIER
knn = KNeighborsClassifier()
#TRAINING DATA
knn.fit(x_train,y_train)
#OBTAINING ENDING TIME
knnend_time = current_milli_time()
#TOTAL DURATION
knnduration=knnend_time - knnstart_time
#PREDICTING DATA
y_pred_knn = knn.predict(x_test)
#CONFUSION MATRIX
cm_knn = confusion_matrix(y_test,y_pred_knn)
#ACCURACY RATE
ar_knn = calculate_AR(cm_knn)
ar_knn

0.5517241379310345

In [181]:
#CONFUSION MATRIX OF KNN
print(cm_knn)

[[ 1 11]
 [ 2 15]]


## Decision Tree

In [172]:
model2 = DecisionTreeClassifier()
e = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
#df['classification'] = le.fit_transform(df['classification'])

# Split the data into features and target
X = df[['Survived','Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex']]
y = df['classification']



# Fit the model to the data
model2.fit(X, y)

# Predict the class labels for the data
predictions = model2.predict(X)
prediction_DecisionTree = model2.score(X, y)
# Print the accuracy of the model
print( prediction_DecisionTree )


# Create a confusion matrix
cm = confusion_matrix(df['classification'], predictions)

# Print the confusion matrix
print(cm)

1.0
[[47  0  0  0]
 [ 0  4  0  0]
 [ 0  0 58  0]
 [ 0  0  0 35]]


## Accuracy

In [173]:
# Printing the results
print("")

print("Logistic Regression", accuracy_regression)
print("Random Forest Classifation", ar_rfc)
print("Decision Tree Classifier", prediction_DecisionTree)
print("Naive Bayes Classifier", ar_nb)
print("KNN Classifier", ar_knn )



Logistic Regression 0.9791666666666666
Random Forest Classifation 0.7241379310344828
Decision Tree Classifier 1.0
Naive Bayes Classifier 0.7931034482758621
KNN Classifier 0.5517241379310345
